export const HOME_SUBMIT_BEGIN = 'HOME_SUBMIT_BEGIN';
export const HOME_SUBMIT_SUCCESS = 'HOME_SUBMIT_SUCCESS';
export const HOME_SUBMIT_FAILURE = 'HOME_SUBMIT_FAILURE';
export const HOME_SUBMIT_DISMISS_ERROR = 'HOME_SUBMIT_DISMISS_ERROR';
